apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cluster-1
  namespace: reference-ns
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: tanzu-standard-storage
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 4Gi
      tkr:
        reference:
          name: photon-3-k8s-v1.22.9---vmware.1-tkg.1
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-medium
      storageClass: tanzu-standard-storage
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 16Gi
      tkr:
        reference:
          name: photon-3-k8s-v1.22.9---vmware.1-tkg.1
    - name: worker-nodepool-a2
      replicas: 1
      vmClass: best-effort-small
      storageClass: tanzu-standard-storage
      tkr:
        reference:
          name: photon-3-k8s-v1.22.9---vmware.1-tkg.1
  settings:
    storage:
      defaultClass: tanzu-standard-storage
